<a href="https://colab.research.google.com/github/spy129/MAT494/blob/main/HW1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Charpet 1.2 Elements of Linear Algebra

In [20]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a = np.zeros(5)
b = np.ones(5)
c = np.zeros(5) + 3
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3.]


In [22]:
a = np.random.rand(10)
print(a)

[0.46537067 0.01355543 0.8144012  0.37674346 0.04254418 0.0372759
 0.41715546 0.511423   0.69120626 0.24719012]


In [23]:
a = np.arange(10)
print(a)
print(a[-2])
print(a[1:3])
print(a[1:5:3])

[0 1 2 3 4 5 6 7 8 9]
8
[1 2]
[1 4]


In [24]:
a = np.zeros((2,5))
print(a,'\n')
print('len=',len(a))
print('shape=',a.shape)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len= 2
shape= (2, 5)


In [25]:
a = np.zeros((2,5))
print(a,'\n')
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

nx = 2
ny = 5


In [26]:
a = np.zeros((2,5)) + 7
print(a,'\n')
a = np.ones((2,5)) + 7
print(a,'\n')
a = np.full((2,5),7)
print(a,'\n')

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]] 



In [27]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

[[1 1]
 [1 1]]
int64


In [30]:
a=np.array(([1.,1],[1,1]))<2
print(a)
print(a.dtype)

[[ True  True]
 [ True  True]]
bool


In [31]:
a=np.array(([1,1],[1,1]),dtype=float)
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64
